[project]
name = "uv-sleeper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
    "textual>=6.6.0",
]

[dependency-groups]
dev = [
    "ipython>=9.7.0",
]
